import { createHash, randomBytes } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

export const MODELS = [
  { id: 'whisper-tiny-multilingual-int8', url: 'https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-whisper-tiny.tar.bz2', bytes: 116204861, sha256: 'c46116994e539aa165266d96b325252728429c12535eb9d8b6a2b10f129e66b1' },
  { id: 'silero-vad-2026', url: 'https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx', bytes: 643854, sha256: '9e2449e1087496d8d4caba907f23e0bd3f78d91fa552479bb9c23ac09cbb1fd6' },
];
const modelFile = (root, item) => path.join(root, 'models', `${item.id}.model`);
async function verified(file, item) { try { const data = await fs.readFile(file); return data.length === item.bytes && createHash('sha256').update(data).digest('hex') === item.sha256; } catch { return false; } }
async function extract(archive, root) { await fs.mkdir(path.join(root, 'runtime', 'asr'), { recursive: true, mode: 0o700 }); await new Promise((resolve, reject) => { const child=spawn('tar',['-xjf',archive,'-C',path.join(root,'runtime','asr'),'--strip-components=1','sherpa-onnx-whisper-tiny/tiny-encoder.int8.onnx','sherpa-onnx-whisper-tiny/tiny-decoder.int8.onnx','sherpa-onnx-whisper-tiny/tiny-tokens.txt']); child.once('exit',code=>code===0?resolve():reject(new Error(`stt_extract_failed:${code}`))); child.once('error',reject); }); await fs.copyFile(modelFile(root, MODELS[1]),path.join(root,'runtime','silero_vad.onnx')); }
export async function status(root) { const ready = await Promise.all(MODELS.map(item=>verified(modelFile(root,item),item))).then(all=>all.every(Boolean)); const sizeBytes = (await Promise.all(MODELS.map(item=>fs.stat(modelFile(root,item)).then(s=>s.size).catch(()=>0)))).reduce((a,b)=>a+b,0); return { ready, modelName: 'IRIS Whisper tiny multilingual', modelPath: path.join(root,'runtime'), sizeBytes }; }
export async function download(root, signal, progress=()=>{}) { await fs.mkdir(path.join(root,'models'),{recursive:true,mode:0o700}); let offset=0; const total=MODELS.reduce((sum,item)=>sum+item.bytes,0); for (const item of MODELS) { const destination=modelFile(root,item); if (await verified(destination,item)) { offset+=item.bytes; continue; } const response=await fetch(item.url,{signal}); if(!response.ok||!response.body) throw new Error(`stt_download_http_${response.status}`); const temporary=`${destination}.${randomBytes(8).toString('hex')}.part`; const handle=await fs.open(temporary,'wx',0o600); const hash=createHash('sha256'); let received=0; try { for await (const chunk of response.body) { if(signal?.aborted) throw new Error('stt_download_canceled'); const bytes=Buffer.from(chunk); received+=bytes.length; if(received>item.bytes) throw new Error('stt_size_mismatch'); hash.update(bytes); await handle.write(bytes); progress({type:'progress',downloaded:offset+received,total}); } } finally { await handle.close(); } if(received!==item.bytes||hash.digest('hex')!==item.sha256){await fs.rm(temporary,{force:true});throw new Error('stt_checksum_mismatch');} await fs.rename(temporary,destination); offset+=received; }
 await extract(modelFile(root,MODELS[0]),root); return status(root); }
export async function transcribe(root, wavPath) { const sherpa = await import('sherpa-onnx-node'); const wav=sherpa.readWave(wavPath); if(!wav?.samples) throw new Error('stt_wav_required'); let samples=wav.samples; if(wav.sampleRate!==16000) samples=new sherpa.LinearResampler(wav.sampleRate,16000).resample(samples); const runtime=path.join(root,'runtime'); const recognizer=await sherpa.OfflineRecognizer.createAsync({featConfig:{sampleRate:16000,featureDim:80},modelConfig:{whisper:{encoder:path.join(runtime,'asr','tiny-encoder.int8.onnx'),decoder:path.join(runtime,'asr','tiny-decoder.int8.onnx'),language:'auto',task:'transcribe',tailPaddings:-1},tokens:path.join(runtime,'asr','tiny-tokens.txt'),numThreads:2,provider:'cpu',debug:false}}); const stream=recognizer.createStream(); stream.acceptWaveform({samples,sampleRate:16000}); return (await recognizer.decodeAsync(stream)).text?.trim()||''; }
